_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.12.4
        t:
            "1":
                - 55
            "2":
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.12.4
            "5": 0.19.7
            "8":
                - 3
                - 5
            "12": 0.19.7
            "13": windows-amd64
activation:
    value: sigmoid
batch_size:
    value: 4
beta:
    value: 0.5
beta1:
    value: 0.5
beta2:
    value: 0.5
dataset:
    value: fashion-mnist
epochs:
    value: 1
epsilon:
    value: 1e-06
hidden_size:
    value: 4
learning_rate:
    value: 0.1
loss:
    value: cross_entropy
momentum:
    value: 0.5
num_layers:
    value: 1
optimizer:
    value: sgd
wandb_entity:
    value: amar74384-iit-madras
wandb_project:
    value: DA6401_assign_2
weight_decay:
    value: 0
weight_init:
    value: random
